# Generated by Django 5.2.5 on 2025-08-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ganancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='porcentaje_ganancia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='total_inversion',
        ),
    ]
