# Generated by Django 5.2.7 on 2025-10-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_ganancia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleItem',
            new_name='DetalleVenta',
        ),
        migrations.RenameModel(
            old_name='Sale',
            new_name='Venta',
        ),
    ]
